### ISSUE TITLE
Internationalization/i18n support

### ISSUE THREAD

**Issue by felipe-guedes** [SAP/ui5-webcomponents-sample-react#19]
Is there a easy way internationalize SAP UI5 webcomponents for react accordingly with SAP standards? Perhaps using web-components-core?

Thank you.

**Comment by fifoosid** [comment]
Hi @felipe-guedes 

UI5 web components come with built in internationalisation. In order to make use of it, you have to configure the language in your application. There are two ways of doing it:

1. Set the language as parameter in your URL(using ```sap-ui-language``` parameter): 
For example, if you need english you can set it like this: ```www.example.com/home?sap-ui-language=en```

2. Set the language in configuration:
Here is a sample configuration:
```html
<script data-ui5-config type="application/json">
{
	"rtl": true,
	"compactSize": true,
	"language": "ja",
}
</script>
```

The language in the sample is set to Japanese. For more info check out our [docs](https://github.com/SAP/ui5-webcomponents/blob/master/docs/Configuration.md)


PP: To make internationalisation work, you need to package our translations in the bundle of your app.

Best regards,
Filip
