### ISSUE TITLE
ui5-input text value should be cleared after "Add Todo" is clicked

### ISSUE THREAD

**Issue by TianyuanC** [SAP/ui5-webcomponents-sample-react#21]
Is it possible to clear the text input value after the `Add Todo` action?
 
![image](https://user-images.githubusercontent.com/12591144/66964849-a2ad3b80-f02c-11e9-9703-c1c578273298.png)

I've tried to clear the `this.todoInput.current.value`, but it doesn't seem to clear the input text field, is there any better way to do it?

Thanks so much!

**Comment by fifoosid** [comment]
Hi @TianyuanC 

Yes, it is possible to clear the input field, and it is done exactly the way you are trying to.

The problem was coming from the ui5-input and it was resolved in our latest version. The following PR #22 updated the version in this app and resolves the problem. Now you can empty the input via ```this.todoInput.current.value```

Best regards,
Filip

**Comment by TianyuanC** [comment]
Thanks for updating the project!

I found the following appear to be a reliable way of clearing input during `handleAdd`, 
`this.todoInput.current.getInputDOMRef().value = ""`

Cheers!

**Comment by fifoosid** [comment]
```todoInput.current.value = ""``` is all that you need.

Please make sure that you fetch the latest changes from master, then delete your node_modules folder and run npm install again, so that you can get the latest UI5 Web Components version.
